### ISSUE TITLE
Incorrect S3 bucket name

### ISSUE THREAD

**Issue by thughes** [dancrumb/generator-serverless-policy#1]
I have a serverless service with a semi-long name. For illustration let's call it `serverless-my-long-name`.

When I deployed, the S3 bucket that was created was named something like `serverless-my-long-name-serverlessdeploymentbuck-1234567890123`. Note that the last two letters in `bucket` are missing. As a result, the generated IAM policy that included `arn:aws:s3:::serverless-my-long-name*serverlessdeploymentbucket*` didn't work. It looks like the max length for an S3 bucket name is [63 characters](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html), so I guess the CloudFormation template is truncating the name to be able to add the random characters on the end.

**Comment by dancrumb** [comment]
Good point. I'll need to dig into how serverless is handling this

**Comment by dancrumb** [comment]
Unfortunately, I think this is a consequence of https://github.com/serverless/serverless/issues/2791

I'm not going to modify this until serverless have figured out what they are going to do with their bucket names...
