### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by gseva** [dancrumb/generator-serverless-policy#10]
Hi! 

Could you please update the version of the package, so the `npm install` includes last changes (like this one https://github.com/dancrumb/generator-serverless-policy/pull/9).

**Comment by guzart** [comment]
Meanwhile: 
```bash
npm install -g https://github.com/dancrumb/generator-serverless-policy/tarball/master
```

**Comment by dancrumb** [comment]
Version 1.8.0 is live
