### ISSUE TITLE
Policy for scheduled events could use some tweaking

### ISSUE THREAD

**Issue by smcoll** [dancrumb/generator-serverless-policy#15]
Seems like there could be some improvements to support the `schedule` event type.

Given a `serverless.yml` config essentially like this:

```
service: myservice
frameworkVersion: "=1.45.1"

functions:
  myfunc:
    events:
      - schedule: rate(1 minute)
```

The `events` policies generated look like this:

```
    {
      "Effect": "Allow",
      "Action": [
        "events:Put*",
        "events:Remove*",
        "events:Delete*"
      ],
      "Resource": [
        "arn:aws:events:*:*:rule/myservice-*-us-east-1"
      ]
    },
```

But i found this error, on `sls deploy`:

-  An error occurred: MyfuncEventsRuleSchedule1 - User: arn:aws:iam::<REDACTED>:user/serverless-agent is not authorized to perform: events:DescribeRule on resource: arn:aws:events:us-east-1:<REDACTED>:rule/myservice-dev-MyfuncEventsRuleSchedule1-1VUFLZR5PHGXL (Service: AmazonCloudWatchEvents; Status Code: 400; Error Code: AccessDeniedException; ...

i changed that portion to the following, to resolve that (added `events:DescribeRule` and changed the resource value):

```
    {
      "Effect": "Allow",
      "Action": [
        "events:Put*",
        "events:Remove*",
        "events:Delete*",
        "events:DescribeRule"
      ],
      "Resource": [
        "arn:aws:events:*:*:rule/myservice-*"
      ]
    },
```
Thanks for writing this generator.

**Comment by dancrumb** [comment]
Could you create a pull request and I'll approve it
