### ISSUE TITLE
Account restriction?

### ISSUE THREAD

**Issue by jplock** [dancrumb/generator-serverless-policy#25]
Would it be possible to provide an account ID instead of using `*` in the ARNs?

**Comment by dancrumb** [comment]
Definitely - a PR would be most welcome

**Comment by mvrioe** [comment]
Hi Dan, I created a PR to address this [here](https://github.com/dancrumb/generator-serverless-policy/pull/35)
Regards!

**Comment by dancrumb** [comment]
Thanks to @mespinozas !
