### ISSUE TITLE
[enhancement] add optional SSM permissions

### ISSUE THREAD

**Issue by RYFN** [dancrumb/generator-serverless-policy#50]
When running serverless deploy using this IAM policy, if you're using AWS SSM (e.g. `${ssm:/your-variable/example~true}`, serverless is unable to pull in the SSM variables.

This can be resolved by adding in the IAM permissions outlined in https://github.com/serverless/serverless/issues/5781

**Comment by dancrumb** [comment]
Good enhancement.

I won't get to this personally for a while but would welcome a PR
