### ISSUE TITLE
Is IAM Full access required?

### ISSUE THREAD

**Issue by sime** [dancrumb/generator-serverless-policy#6]
Hi,

Trying to lock down serverless deployment policy, is there any chance that IAM Full Access is not mandatory ? Even after the initial creation of the stack?

**Comment by dancrumb** [comment]
@sime I would guess that it could probably be locked down, but the absence of clear guidance from AWS kind of makes this tricky.

I'm open to a PR if you can point to details an what is necessary and what is unnecessary.

**Comment by sime** [comment]
I'm pretty new to IAM Policies but if I come up with anything I'll share my findings.
