### ISSUE TITLE
Put bucket policy is denied

### ISSUE THREAD

**Issue by kyleawayan** [dancrumb/generator-serverless-policy#63]
After generating a policy with S3 enabled, I tried to deploy the hello-world example for Severless. Serverless said
```
An error occurred: ServerlessDeploymentBucketPolicy - API: s3:PutBucketPolicy Access Denied.
```
I had to manually edit the policy on the AWS console and allow it. It worked after.

By the way, I'm new to Serverless. The first time I ran the generator, I disabled S3 access since I plan not to use S3 for the Serverless function. It looks like Serverless needs it regardless to upload the files. I'm not sure if that should be a default option or not.

Thanks though for making this!

**Comment by ryanrhee** [comment]
I think this is fixed in master, via https://github.com/dancrumb/generator-serverless-policy/pull/35 - but there hasn't been a release with the latest changes.

@dancrumb can we cut a new release?

**Comment by ryanrhee** [comment]
in the mean time, for everyone else, you can get the fixes by installing the master branch:

```console
$ npm install generator-serverless-policy@dancrumb/generator-serverless-policy#master
```

**Comment by dancrumb** [comment]
Hey folks,

I'm on vacation until Friday, so I'll get to this next week.

Also, if anyone is interested in helping maintain this repo, please open an
issue and we can discuss.

Thanks

Dan

**Comment by dancrumb** [comment]
Hey folks;

Sorry - moving house, kids back to school, etc. etc.

v3.1.2 is now released so closing this issue
