### ISSUE TITLE
Extra permissions

### ISSUE THREAD

**Issue by threesquared** [dancrumb/generator-serverless-policy#7]
Not sure if it was just my use case but I had to add the following permissions to the generated policy to get this to work:

`cloudformation:ValidateTemplate`
`apigateway:PATCH`
`ec2:DeleteNetworkInterface`	
`ec2:DescribeNetworkInterfaces`

**Comment by sime** [comment]
Also `logs:DeleteLogGroup` is missing for rollback / remove.

**Comment by vicente-valls** [comment]
Also `"cloudformation:DescribeStackResources"`

**Comment by bootstraponline** [comment]
`"cloudformation:ValidateTemplate"` is required for deploys.

**Comment by dancrumb** [comment]
I'd happily accept a PR for these

**Comment by bvanderlugt** [comment]
@dancrumb I these changes have been addressed in the code but the npm version number needs to be bumped: #10

**Comment by dancrumb** [comment]
Version 1.8.0 is live
